cuda_id: '0'
multi_cuda: 0 # 0: don't use multi; 1: use
seed: 42

model: resnet50
num_features: 2048
batch_size: 12

optim: SGD # SGD or Adam
loss: Recall # Recall loss and CE loss
num_workers: 4

dataset: 
  name: breast_train
  path: ./save/init_data/ # u need to change
  size: 224
  tile_size: 1024
  num_class: 3

# SPR
num_classes: 3
num_classes_sub: 3

# noise param
noise_rate: 0.3
noise_method: 'nearly' # symmetric; pairflip; nearly;
noise_range: all # all: both labeled and unlabeled ; labeled: only labeled sample; 
methods: Both #BMM、SRP 和 Both

# train iteration param
pretrained_iteration: 5   #!!!!this is what we changed for a better solution
max_iteration: 4

# cluster param
Kmeans_cluster: 10           #!
Kmeans_Visual_cluster: 8
CC_cluster: 3
PCA_components: 256
Knn_act: 0 # 1: use knn; 0:don't use knn
Knn_number: 1 # neighbors number 

# Grad-CAM
grad_save: 0
# 
visual_method: tsne
# paths
save_data_dir: ./Data
logger_path: ./logs
save_param_dir: ./param




